If successful, store data on local storage
alexKwonIsAwesome/issue-creator pull request #2
Opened 2019-08-01 11:51 UTC by jonghwajoa

api요청 성공시 토큰과 유저아이디를 로컬스토리지에 저장합니다.
로컬스토리지에 아이디와 토큰이 존재한다면 자동으로 입력되도록 구현해봤습니다.
react를 잘몰라서 구현이 엉망일수도 있으니.. 코드한번 봐주시면 감사하겠습니다.

function 컴포넌트? 에서 class 컴포넌트로 바꿨습니다..
테스트결과 잘동작했습니다.~

2019-08-01 13:26 UTC, hyokualexkwon requested changes
언급한 일부분에 대해 조금만 더 코드가 수정되면 될것같습니다!
노고에 감사드립니다 😁

2019-08-01 13:26 UTC, alexKwonIsAwesome commented on src/Main.js
> +        ...this.state,
함수형 컴포넌트에서 state를 변경할 때에는 변경하지 않는 내용의 state까지 작성해야 하지만, 클래스 기반 컴포넌트의 경우에 사용하는 this.setState에는 변경하고자 하는 값만 작성하면 됩니다. 따라서 해당부분의 코드는 없어도 됩니다!

2019-08-01 13:26 UTC, alexKwonIsAwesome commented on src/Main.js
> +        ...this.state,
여기도 위와 같은 이유로 없어도 됩니다!

2019-08-01 13:26 UTC, alexKwonIsAwesome commented on src/Main.js
> +        isLoading: true
생성 실패 케이스에는 로딩 상태를 false로 바꿔야 할것 같습니다!

2019-08-01 13:26 UTC, alexKwonIsAwesome commented on src/Main.js
> +      ...this.state,
ㅎㅎ 여기둥 ㅎㅎ

2019-08-01 13:26 UTC, alexKwonIsAwesome commented on src/Main.js
> +                        value={token ? token : ''}
해당 부분에서는 `value={token}`으로 작성하고 차라리 초기 state를 작성하는 부분에서 조건을 작성하는게 더욱 직관적일것 같습니다.

```
    const { localStorage } = window;
    const storageToken = localStorage.getItem('token');
    const storageUserId = localStorage.getItem('userId');

    this.state = {
      token: storageToken ? storageToken : '',
      userId: storageUserId ? storageUserId : '',
      day: '',
      checklist: '',
      isLoading: false
    };
```

차라리 이런식이면 어떨까용?

2019-08-01 13:26 UTC, alexKwonIsAwesome commented on src/Main.js
> +                        value={userId ? userId : ''}
위와 같은 내용입니다.

2019-08-01 14:19 UTC, jonghwajoa commented on src/Main.js
> +                        value={token ? token : ''}
```js

2019-08-01 14:20 UTC, jonghwajoa commented on src/Main.js
> +        ...this.state,
오 그렇군요..  감사합니다!

2019-08-01 14:23 UTC, jonghwajoa commented on src/Main.js
> +        isLoading: true
반영했습니다. 감사합니다

2019-08-01 14:33 UTC, jonghwajoa commented
피드백 감사합니다.

2019-08-01 14:43 UTC, jonghwajoa commented on src/Main.js
> +                        value={token ? token : ''}
막상 이렇게 수정하고보니 제안하신것처럼 삼항연산자가 더 명확해 보이기도하고 고민되네요
```js
 token: storageToken ? storageToken : '',
```

2019-08-01 16:16 UTC, jonghwajoa commented on src/Main.js
> +                  <Submit type="submit" disabled={false} value={isLoading ? '생성 중...' : '생성하기'} />
실수... 다음 커밋에서 수정했습니다..ㅠ

2019-08-02 00:48 UTC, alexKwonIsAwesome commented on src/Main.js
> +                        value={token ? token : ''}
상관 없을것 같습니다 ㅋㅋㅋ

2019-08-02 00:50 UTC, hyokualexkwon approved these changes
감사합니다!

2019-08-02 00:50 UTC, merged